#!/usr/bin/env python3
"""Build a self-contained audit; does not modify training."""
from pathlib import Path
import json,html,hashlib,subprocess,re,datetime
import yaml
R=Path('/root/gpufree-data/projects/HUMANOID_TW');D=Path('/root/gpufree-data/datasets/practice9');S=D/'tw75_train_v1';N=D/'tw75_dataset_v1/native_training_geometry';M=R/'source/unitree_rl_lab/unitree_rl_lab/tasks/mimic';A=R/'source/unitree_rl_lab/unitree_rl_lab/assets/robots'
O=R/'validation_artifacts/tw81_training_method';O.mkdir(parents=True,exist_ok=True)
def read(p):return Path(p).read_text(encoding='utf-8')
def esc(v):return html.escape(str(v))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def p(s):return '<p>'+s+'</p>'
def pre(s):return '<pre>'+esc(s)+'</pre>'
def table(h,rows):return '<div class="table"><table><thead><tr>'+''.join('<th>'+esc(x)+'</th>' for x in h)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(x)+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
sections=[]
def sec(k,t,b,q):sections.append((k,t,b,q))
runs={s:sorted((R/'logs/rsl_rl/unitree_custom_humanoid_30dof_mimic_humanml3d').glob('*_tw75_full_s'+s))[-1] for s in ['42','123']}
env=yaml.load(read(runs['42']/'params/env.yaml'),Loader=yaml.BaseLoader)
now=datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=8))).isoformat(timespec='seconds');commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip();runtime={};rows=[]
for s,run in runs.items():
 log=read(S/f'seed{s}/train.log');its=re.findall(r'Learning iteration (\d+)/(\d+)',log);eta=re.findall(r'ETA: ([0-9:]+)',log);state=read(S/f'seed{s}/status').strip();it=its[-1] if its else ('?','?')
 runtime[s]={'run':str(run),'status':state,'iteration':it,'eta':eta[-1] if eta else None,'source_commit':read(S/f'seed{s}/source_commit').strip()};rows.append([s,state,' / '.join(it),eta[-1] if eta else '—'])
sec('scope','01 · 范围与运行快照',p('本文审计 TW-75 当前正式训练，供 TW-81 逐项审阅。目标：稳定走路与站立中的手部表达，暂不做蹲坐切换。实际配置、实现限制和未来建议分开说明。本次只生成文档，不修改或重启训练。')+p('快照时间 '+now+'；代码基线 <code>'+commit+'</code>。状态不是实时看板。')+table(['种子','状态','累计迭代 / 目标','日志ETA'],rows)+p('两张4090分别跑seed42/GPU0、seed123/GPU1，每组1024环境；模型、优化器独立，无梯度同步。completed表示训练脚本中的训练、回放和视频结束，不等于任务验收通过。'),'本阶段范围与交付目标是否准确？')
sec('flow','02 · 完整流程与控制目标',p('人体NPY/文本/官方划分 → 类别与来源审计 → C++重定向 → 28到30坐标映射 → 质量审核与时间拉伸 → Isaac FK → 类别平衡manifest → PPO接触动力学训练 → 留出动作回放与视频。')+p('策略读取当前参考状态与机器人状态，输出30维关节位置动作，经目标限速与PD执行。训练机器人受模拟重力、惯性和地面接触影响。离线FK/人体对照视频属于运动学检查，不能替代动力学验收。文本仅用于离线选数据；当前是参考条件跟踪器，不是文本动作生成器，无独立的风格判别器。'),'是否还需要自主生成动作或显式动作切换？')
summary=json.loads(read(R/'validation_artifacts/tw75_training_launch/dataset_summary.json'))
sec('data','03 · 数据与划分',p('扫描29228数组=14614原始+镜像；镜像不作为独立样本。选取走路/站立上肢相关类别的全部候选，无top-N上限；不是整个HumanML3D所有类别。源NPY：'+str(D/'humanml3d_rebuild/staging-v1/HumanML3D/new_joints')+'；文本与官方划分在 /root/gpufree-data/datasets/HumanML3D-official/HumanML3D。')+table(['阶段','规则'],[['文本','优先walk/march/pace；否则arm/hand/wave/gesture/clap/point/salute或stand/stationary/idle归站立上肢。合并所有描述后判断。'],['排除','跑跳、舞蹈、坐蹲跪爬躺、踢拳、楼梯/椅子/游泳等关键词；混合描述可能被整体排除。'],['数组','[T,22,3]，至少40帧，数值有限，源20Hz。'],['站立几何','根水平路径≤.30m，高度变化≤.12m，脚水平跨度≤.20m。'],['来源隔离','沿用官方划分；去掉410条与val/test原始录制来源相同的train片段。未额外证明val/test彼此来源隔离。'],['候选','5900：train3090/1548、val218/100、test644/300（走路/站立）。'],['膝弯曲','standing_upper双膝角集合p90≤40°；排除126条，5774条送重定向。不是每帧直立保证。'],['最终','质量/FK后5361条；实际划分如下。']])+table(['集合','走路','站立','总数','参考帧数'],[[k,v['counts']['walking'],v['counts']['standing_upper'],sum(v['counts'].values()),v['frames']] for k,v in summary.items()])+p('训练4209条、4981348帧=约27.67小时处理后50Hz参考，含减速拉伸，不能当作原始录制总时长。标签为启发式，可能误分或漏掉动作。'),'类别覆盖、过滤规则、来源隔离是否足够？')
sec('retarget','04 · 重定向与几何',p('采用指定tw_retargeting原生C++ QP方法：stream模式、iterations=1、原生90Hz输出，再线性重采样50Hz。求解器几何从修正后urdf0711_training_30dof.urdf派生；关节限位与肢段长度来自训练模型，修正chest坐标框架和任务朝向，保留原方法。')+p('q_training=sign×q_native+offset；28求解器关节映射30自由度，两侧foot_roll参考为0。坐标契约tw44_table_v2。派生模型100随机姿态FK矩阵等价误差记录为0；这不是人体重定向零误差。QP KKT残差需有限且≤1e-6。')+pre(read(N/'configs/selected_head_axis.json'))+p('上述position-scale/posture-bias/acceleration-cost是离线重定向参数，不是RL奖励。mean-distance-mm=5不是全部动作通过5mm认证。完整原生实现与映射表见附录。'),'几何、零位、坐标与重定向目标权重是否正确？')
sec('reference','05 · 参考数据处理',p('源[x,y,z]转机器人[z,x,y]，初始髋横向对齐−Y并保留后续转向。根相对第一帧平移缩放0.28963，名义高度0.28m；双髋方向恢复yaw，根参考未恢复完整roll/pitch。28→30映射后按URDF限位裁剪并记录比例；本轮要求clipped_fraction=0。')+pre('s=max(1, joint_p99_ratio/.9, joint_peak_ratio/1.2, root_xy_p99/.6, root_xy_peak/.8, root_yaw_p99/2, root_yaw_peak/3)')+p('每片时间拉伸最多6倍，超过需求上限则质量失败。关节、根平移、展开的yaw同步线性插值，输出50Hz，再求新时间轴导数。控制50Hz不表示人体原速；本轮没有逐渐加速课程。'),'根缩放、倾斜简化和动作节奏是否合理？')
sec('quality','06 · 质量门槛与FK',table(['检查','实际规则'],[['近限位','距边界≤max(.001rad,关节范围1%)；任一关节占比>5%或连续>.25s为严格失败。'],['关节速度','超速元素占比≤.5%，每关节p99速度比例≤1，峰值≤1.2。'],['根速度','水平p99≤.6、峰值≤.8m/s；yaw p99≤2、峰值≤3rad/s。'],['当前例外政策','用户视觉审阅后仅near_limit_fraction/run允许提示，保留strict_quality_pass、原始原因及acceptance_policy。按本轮政策quality_pass不等于原严格全通过。'],['FK','Isaac写入参考状态、批量128求身体位姿速度，非动力学接触验证。'],['地面','以整段双脚碰撞包围角点最低值计算一个固定Z偏移，使最低处=1mm；非逐帧贴地，仍可能悬空或滑脚。'],['FK门槛','base/root状态误差≤1e-5；速度与差分的一致性p95线速度≤.05m/s，角速度≤.2rad/s。']])+p('政策tw75_user_review_20261003_near_limits_advisory。FK batch1与128关节角速度相同、身体位置最大差1.62e-6m；启动记录83项测试通过。门槛不保证完整支撑时序或语义正确。'),'哪些质量提示需要收紧？')
sec('sampling','07 · 采样与episode',p('类别重置先验走路/站立各50%，类内片段等权；weight=.5/类片段数/(frames−1)，抵消长片段起始帧数偏置。adaptive_uniform_ratio=1，本轮不混失败驱动采样。')+p('随机片段、随机起始帧，用参考根/关节状态初始化再加扰动。参考每策略步前进1帧；片尾终止重置，不无缝接另一个动作。训练episode上限30秒，runner初始episode长度随机化。50/50是重置概率，不保证实际帧数或时间占比各半。curriculum=None，固定混合训练。'),'需不需要类内困难样本、完整起步或动作切换？')
sec('physics','08 · 动力学与执行器',p('30自由度浮动基座、平地重力接触、convex_hull碰撞、自碰撞关闭、固定关节合并；位置/速度求解迭代8/4。质量取URDF约0.841kg；资产初始Z=.264m，episode重置由参考覆盖。电机未选定，以下是仿真假设。')+table(['组','Kp','Kd','力矩N·m','速度rad/s','armature','动作尺度rad'],[['主要腿含ankle_yaw',20,1,40,3,.001,.5],['ankle_pitch/foot_roll',10,.5,15,3,.001,.375],['腰',10,.5,20,2,.001,.5],['臂',5,.25,8,2,.0005,.4],['颈',3,.15,3,2,.0002,.25]])+p('ImplicitActuator由物理引擎执行PD，无指定电机电流环、热限制、真实力矩转速曲线或通信延迟。地面静/动摩擦1/1、multiply组合；soft_joint_pos_limit_factor=1。USD force_usd_conversion=False允许缓存，URDF哈希不等于重新认证已加载USD。'),'电机假设、自碰撞关闭与碰撞体是否合适？')
sec('control','09 · 控制频率与动作',p('物理dt=.005s=200Hz，decimation4；策略/观测/目标50Hz，目标保持4物理步。不是硬件电流环频率。')+pre('q_raw = default_joint_position + action_scale * action\ndelta = clamp(q_raw-q_previous_target, ±velocity_limit*.02*.5)\nq_target = q_previous_target + delta\nPD + physics -> actual state')+p('tau=0无指数低通，目标变化率限制启用；腿/脚每步最多.03rad，腰/臂/颈.02rad，即1.5/1rad/s。不是实际速度保证或参考统一减半。重置记忆从实际角初始化。动作相对默认姿态，不是参考角残差；clip_actions=null，变化率限制不等于绝对幅度裁剪。'),'目标限速是否压制拟人快速动作？')
obs=[['motion_command',60,'参考30角+30角速度','无'],['motion_anchor_pos_b',3,'参考chest相对实际chest位置','无'],['motion_anchor_ori_b',6,'相对旋转矩阵前两列','±.03'],['base_lin_vel',3,'基座局部线速度','±.10m/s'],['base_ang_vel',3,'基座局部角速度','±.15rad/s'],['anchor_lin_vel_error_b',3,'chest局部参考减实际线速度','无'],['anchor_ang_vel_error_b',3,'chest局部参考减实际角速度','无'],['joint_pos_rel',30,'实际角减默认角','±.01rad'],['joint_vel_rel',30,'实际速度减默认速度','±.30rad/s'],['last_action',30,'上一步动作','无']]
sec('obs','10 · 观测与随机化',p('Actor171维、Critic291维，已核对日志；无RNN、历史堆叠或未来多帧参考。')+table(['Actor项','维度','含义','均匀噪声'],obs)+p('Critic含command60、锚点位置3/朝向6、14刚体相对位置42/朝向84、基座速度各3、关节角/速度各30、动作30，无上述显式噪声。')+table(['阶段','范围'],[['启动一次','静摩擦.7–1.3、动摩擦.6–1.1、恢复0–.1，共32桶；默认关节角±.005rad；chest质心各轴±.002m。'],['重置根姿态','x/y±.02m，z±.005m，roll/pitch±.05rad，yaw±.10rad。'],['重置根速度','x/y±.25m/s，z±.10m/s，roll/pitch±.25rad/s，yaw±.40rad/s。'],['重置关节','参考角±.05rad再clip，参考关节速度。'],['未启用','当前EventCfg无持续推力、延迟、全身质量或电机强度随机化。']])+p('评估关闭观测噪声仍保留材质/重置随机性；实机需要可获得这些状态与参考。'),'观测可用性和随机化是否充分？')
rewards=[[k,v['weight'],v.get('params',{}).get('std','—'),v['func'].split(':')[-1]] for k,v in env['rewards'].items() if isinstance(v,dict)]
sec('rewards','11 · 完整奖励函数',p('指数项r=exp(−E/σ²)，E为平方误差或多刚体/关节均方；朝向为四元数旋转差。σ为敏感度尺度而非硬阈值；位置m、角度rad、速度m/s或rad/s。奖励按策略步长加权积分。')+table(['实际项','权重','σ','实现'],rewards)+p('anchor=chest；core=base_link/chest；leg=双侧thigh/mid_leg/foot，foot重复单独加奖；arm=上臂/前臂/手腕。joint_pos跟踪28参考关节，不含foot_roll；joint_vel_cost是30关节速度误差均方。')+p('相对身体奖励对齐参考水平位置和yaw到实际chest，保留参考高度与相对形态，全局anchor奖另约束整体；身体速度用世界坐标比较。joint_acc/torque为平方和；action_rate为原始动作差平方和，不等于限速后角变化；joint_limit软限位外偏差；foot_roll_default默认角L1。脚接触力历史>1N时惩罚水平滑速；非脚部>1N接触计罚。')+p('<strong>拟人性审阅：</strong>上肢.6权重/.18m尺度比腿1.5/.12m宽松；平均可能掩盖手腕不足。关节角尺度.5rad≈28.6°。减加速度/动作变化可能压制合理快速动作，需看实际各项奖励贡献，不能只比较不同量纲权重。无独立风格判别、参考脚步接触时序、手腕方向专用奖或站立漂移专用奖。'),'需要提高哪些模仿权重、收紧尺度或分组平滑？')
sec('termination','12 · 终止与指标',table(['条件','实际实现'],[['time_out','训练30s，play极长episode，timeout截断'],['motion_end','到片尾，正常终止/timeout'],['anchor_pos','chest参考与实际Z差>.12m'],['anchor_ori','参考/实际chest坐标中重力向量Z分量差>.8；不是.8rad'],['ee_body_pos','任意脚或手腕参考对齐位置与实际Z差>.12m']])+p('异常终止不都等于摔倒，尤其ee可能是手腕。训练随机帧起步，motion_end比例不等于完整片段成功率。reward高、位置误差低或episode长均不能单独证明拟人。'),'仅Z终止是否忽略水平漂移？')
sec('ppo','13 · PPO与续训',table(['项目','配置'],[['算法','RSL-RL PPO / OnPolicyRunner'],['采样','1024环境×24步=24576 transitions/update；24步=.48s'],['更新','5 epochs、4 minibatches，每batch约6144条'],['网络','Actor/Critic各512→256→128、ELU；Gaussian init_std=1、scalar配置'],['归一化','Actor/Critic obs_normalization=false；无RND/对称增强'],['学习率','配置.001，adaptive，desired_KL=.01，运行中非固定'],['回报','gamma=.99、GAE lambda=.95'],['损失','clip=.2，value系数1、clipped value loss=true，entropy=.005'],['优化器','Adam，max_grad_norm=1'],['恢复','S2 long_velocity/model_15596.pt，actor/critic/optimizer/iteration一并恢复'],['规模','每组新增20000轮，目标累计35596；500轮保存一次']])+p('每组理论新增491520000条transition，并非独立人体帧；共享同一旧模型起点，不是从零独立训练。runner初始episode长度随机化。完整agent.yaml和control_runtime.json见附录。'),'网络、训练量、起点和实验对照设计是否合理？')
sec('validation','14 · 自动验证与视频',p('每模型取val中每类前3条：走路000039/000139/000211，站立000016/000124/000346；每条seed42/123/2026，关闭观测噪声，记录JSON/NPZ。只有6条、18次回放，不是完整294条val、858条test或5种子验收。')+p('固定动作从第0帧开始，步数max(1000,frames+1)；异常后可能重置重跑，必须按episode统计首轮完整完成，不能把总时长当作成功。test保持留出。')+p('每条视频seed42、1000步约20s；侧面eye=(0,−1.2,.15)，lookat=(0,0,−.03)，跟随tau=.5。需验证实际编码、帧数、姿态与镜头。视频按模拟时间输出，慢动作需检查参考拉伸。')+p('完整验收需动作完成率、终止原因、手腕/全身跟踪、2–8Hz逐关节抖动、滑脚/接触冲击与限幅。旧S2推荐模型28回放有3异常、未满足原5种子验收，不能替代新扩大数据模型验证。'),'应扩大哪些未见动作、种子、噪声及原速条件？')
sec('next','15 · 后续提议，尚未实施',p('先完成当前轮，不中途改配置。之后速度课程可按每片拉伸s_i设r_i=1+α(s_i−1)，α由0到1恢复原时间尺度；需连续相位、关节/根插值、四元数插值、所有速度同步、片尾和随机起始逻辑调整。')+p('依据未见动作跟踪/接触/稳定性推进阶段；先核查目标限速和执行器约束，保持50/200Hz，频率另做实验。可单独对照手腕跟踪、分组平滑、站立漂移支撑和接触时序，避免数据/PD/奖励/速度一次混改。'),'请标记优先级，本文不会自动实施。')
files=[runs[s]/'params'/f for s in runs for f in ['env.yaml','agent.yaml','control_runtime.json']]
files += [R/'scripts/practice9'/f for f in ['audit_tw75_dataset.py','prepare_tw75_training.py','prepare_tw75_training.sh','build_tw75_manifests.py','tw75_sampling.py','build_tw75_solver_model.py','native_retarget.py','retarget_humanml3d.py','custom_motion_to_npz.py','train_tw75_full.sh']]
files += [M/'mdp'/f for f in ['commands.py','motion_library.py','observations.py','rewards.py','joint_velocity_cost.py','terminations.py','smooth_joint_actions.py']]
files += [M/'robots/custom_30dof/humanml3d/tracking_env_cfg.py',A/'custom_humanoid.py',A/'custom_joint_coordinates.py']
files += [N/'src'/f for f in ['robot.cpp','motion.cpp','main.cpp']]+[N/'configs/selected_head_axis.json',N/'derived_model.json',D/'custom_robot/urdf/urdf0711_training_30dof.urdf']
files += [R/'validation_artifacts/tw75_training_launch'/f for f in ['dataset_summary.json','verification.json','fk_batch_equivalence.json']]
files += [R/'scripts/rsl_rl'/f for f in ['train.py','play.py','control_runtime.py']]
lib=Path('/root/gpufree-data/conda_envs/env_isaaclab/lib/python3.11/site-packages/rsl_rl');files += [lib/'runners/on_policy_runner.py',lib/'algorithms/ppo.py']
manifest=[];appendix=''
for i,f in enumerate(files):
 content=read(f);digest=sha(f);manifest.append({'path':str(f),'sha256':digest})
 appendix+='<details id="src'+str(i)+'"><summary>'+esc(str(f))+'</summary><p class="meta">SHA256 '+digest+'</p>'+pre(''.join(f'{n:4d}  {line}\n' for n,line in enumerate(content.splitlines(),1)))+'</details>'
sec('sources','16 · 完整配置与源码证据',p('下列完整文件内嵌于HTML，可离线展开，带路径、行号与SHA256。实际运行配置优先于源码默认值。')+appendix,'正文是否与实现一致？')
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f3f5f8;color:#172738;font:16px/1.8 system-ui,"Microsoft YaHei",sans-serif}nav{position:fixed;width:260px;height:100vh;overflow:auto;background:#112e3d;color:#e4eef3;padding:24px 18px}nav a{display:block;color:#d3e4ea;text-decoration:none;padding:7px 0;font-size:14px}nav a:hover{color:#71e1c5}main{max-width:1300px;margin-left:260px;padding:40px 48px}header{padding:24px 0 32px;border-bottom:3px solid #168776}h1{font-size:36px;line-height:1.35;margin:12px 0}h2{font-size:24px;color:#146c61}section{background:white;padding:28px 32px;margin:24px 0;border:1px solid #dce3e9;border-radius:12px;scroll-margin-top:16px}p{overflow-wrap:anywhere}code{font:13px/1.6 monospace;background:#edf3f6;overflow-wrap:anywhere}pre{font:12px/1.65 monospace;background:#102632;color:#e1f2f3;padding:16px;overflow:auto;max-height:650px;tab-size:4}.table{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:10px 12px;text-align:left;vertical-align:top;border-bottom:1px solid #dce3e9;min-width:85px}th{background:#e9f4f1}tr:nth-child(even){background:#f7f9fa}.review{margin-top:24px;border-top:1px dashed #b6c6cd;padding-top:16px}.review p{font-size:14px;color:#596b76}textarea{width:100%;min-height:80px;border:1px solid #b9c9d1;border-radius:6px;padding:12px;font:inherit}button{background:#146c61;color:white;border:0;border-radius:6px;padding:10px 16px;cursor:pointer}details{margin:12px 0;border:1px solid #dce3e9;padding:10px}summary{cursor:pointer;overflow-wrap:anywhere;font-size:14px}.meta{font-size:13px;color:#586c78}input[type=search]{width:100%;padding:10px;border-radius:6px;border:0;margin:16px 0}@media(max-width:900px){nav{position:static;width:auto;height:auto}nav .links{display:grid;grid-template-columns:1fr 1fr}main{margin:0;padding:20px}section{padding:20px}h1{font-size:28px}}@media print{nav,button,.review{display:none}main{margin:0;padding:0}body{background:white}section{border:0;padding:10px 0}pre{max-height:none;white-space:pre-wrap;overflow-wrap:anywhere;color:black;background:#eee}.table{overflow:visible}h2{break-after:avoid}}'''
nav=''.join('<a href="#'+k+'">'+esc(t)+'</a>' for k,t,_,_ in sections)
body=''.join('<section id="'+k+'"><h2>'+esc(t)+'</h2>'+b+'<div class="review"><label><input type="checkbox" data-key="'+k+'-done"> 已审阅</label><p>'+esc(q)+'</p><textarea aria-label="'+esc(t)+'审阅意见" data-key="'+k+'-note" placeholder="记录疑问、建议与优先级"></textarea></div></section>' for k,t,b,q in sections)
js='''const fields=[...document.querySelectorAll('[data-key]')],prefix='tw81-review-v1:';let storageOK=true;for(const el of fields){try{const v=localStorage.getItem(prefix+el.dataset.key);if(el.type==='checkbox')el.checked=v==='true';else el.value=v||''}catch(e){storageOK=false}el.addEventListener('input',()=>{try{localStorage.setItem(prefix+el.dataset.key,el.type==='checkbox'?el.checked:el.value)}catch(e){storageOK=false}progress()})}function progress(){document.getElementById('progress').textContent='已审阅 '+fields.filter(x=>x.type==='checkbox'&&x.checked).length+' / 16 节'+(storageOK?'':'；浏览器无法保存，请及时导出。')}progress();document.getElementById('export').onclick=()=>{const data={issue:'TW-81',exported_at:new Date().toISOString(),review:Object.fromEntries(fields.map(e=>[e.dataset.key,e.type==='checkbox'?e.checked:e.value]))};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='TW-81-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};document.getElementById('search').oninput=e=>{const q=e.target.value.trim().toLowerCase();for(const s of document.querySelectorAll('main section'))s.hidden=Boolean(q&&!s.textContent.toLowerCase().includes(q))};'''
intro=p('审阅勾选与意见仅保存在当前浏览器localStorage。地址或浏览器变化可能导致记录不可见，请及时导出JSON。不自动写入Linear或更改训练。')+'<button id="export">导出审阅意见 JSON</button> <button onclick="window.print()">打印 / 保存 PDF</button><p id="progress" aria-live="polite"></p>'
page=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>TW-81 · 当前训练方法审阅</title><style>{css}</style></head><body><nav><strong>TW-81 / 方法审阅</strong><input id="search" type="search" aria-label="筛选章节" placeholder="搜索关键词"><div class="links">{nav}</div></nav><main><header><p class="meta">HUMANOID TW · TRAINING AUDIT</p><h1>当前训练方法与流程<br>逐项审阅版</h1><p>数据 · 重定向 · 控制 · 奖励 · PPO · 验证</p><p class="meta">{esc(now)} · 离线自包含 HTML</p>{intro}</header>{body}<footer>TW-81文档交付不代表TW-75或S2训练验收完成。</footer></main><script>{js}</script></body></html>'''
page=re.sub(r'[ \t]+(?=\n)',lambda m: ''.join('&#32;' if c==' ' else '&#9;' for c in m[0]),page)
(O/'index.html').write_text(page,encoding='utf-8')
(O/'evidence.json').write_text(json.dumps({'snapshot_at':now,'code_commit':commit,'runtime':runtime,'sources':manifest,'html_sha256':sha(O/'index.html')},indent=2,ensure_ascii=False),encoding='utf-8')
print(json.dumps({'output':str(O/'index.html'),'bytes':(O/'index.html').stat().st_size,'sections':len(sections),'sources':len(files)},ensure_ascii=False))
